# Site settings
title: anthonywijaya.com - Web Developer, Digital Problem Solver & Self-Proclaimed Tech Aficionado
email: anthony@anthonywijaya.com
description: ""
baseurl: ""
url: "http://anthonywijaya.com"
author: Anthony Wijaya

twitter_username: awjya
facebook_username: awjya
github_username:  anthonywijaya
linkedin_username: awjya
appnet_username: anthonyw

# Build settings
markdown: kramdown
input: GFM
permalink: "blog/:title"
highlighter: rouge
