# Site settings
title: anthonywijaya.com - Web Developer, Digital Problem Solver & Self-Proclaimed Tech Aficionado
email: anthony@anthonywijaya.com
description: "Anthony Wijaya is a Web Developer, Digital Problem Solver & Self-Proclaimed Tech Aficionado. anthonywijaya.com is Anthony's personal website which contains the work he is doing and his best advice on the things he've learned for the web."
baseurl: ""
url: "http://anthonywijaya.com"
author: Anthony Wijaya
twitter_username: awjya
facebook_username: awjya
github_username:  anthonywijaya
linkedin_username: awjya
appnet_username: anthonyw
googleplus_username: 118050898859741583572

# Build settings
markdown: kramdown
input: GFM
permalink: "blog/:title"
highlighter: rouge
